### ISSUE TITLE
[BUG] Task: run error: store.getIndex(IndexType.FRAMES) must not be null

### ISSUE THREAD

**Issue by TopMarko** [Qodat/qodat#13]
I've cloned the latest version of the repository and opened it up in IntelliJ. After checking that everything was setup for Java 17, I select the application > run task. Everything seems to go well until it throws me the following error: `store.getIndex(IndexType.FRAMES) must not be null`
Any help getting this working would be greatly appreciated. 

Here is the full stack:
```
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ExceptionInInitializerError
Caused by: java.lang.ExceptionInInitializerError

	at stan.qodat.Qodat.loadMainController(Qodat.kt:106)
	at stan.qodat.Qodat.start(Qodat.kt:45)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	... 1 more
Caused by: java.lang.NullPointerException: store.getIndex(IndexType.FRAMES) must not be null
	at stan.qodat.cache.impl.oldschool.OldschoolCacheRuneLite.load(OldschoolCacheRuneLite.kt:64)
	at stan.qodat.cache.impl.oldschool.OldschoolCacheRuneLite.<clinit>(OldschoolCacheRuneLite.kt:54)
	... 11 more
Caused by: java.lang.NullPointerException: store.getIndex(IndexType.FRAMES) must not be null
```

**Comment by TopMarko** [comment]
Was a file directory setup related issue
