### ISSUE TITLE
[BUG] Caches from rev209 onward result in crashes.

### ISSUE THREAD

**Issue by LengaJenga** [Qodat/qodat#9]
- [x] I am using the latest version of Qodat
To my knowledge, I am using the most recent version of Qodat, Qodat 0.1.8

## Bug description

Selecting caches either from initial startup, or from "Change Cache" from _after_ rev208 do not work with Qodat, resulting in repeated crashes up startup.

## Steps to reproduce

1. Open Qodat
2. Select the cache `2022-10-11-rev209` or anything from rev209 onward
3. The software will crash on startup and the command prompt will display a variety of errors.

## The current behavior

The software crashes with any cache from rev209 onward

## The expected behavior

The expected behavior is that the software does not crash, and at the very least allows for the viewing/exporting of models.

## Errors from the console
```
E:\Art\2022\!OSRS RESOURCES\StanDev Cache Viewer\new version\qodat-win-0.1.8\qodat-win-0.1.8\bin>
if "" == ""
Picked up _JAVA_OPTIONS: -Xmx20G
Dec. 14, 2022 2:59:16 P.M. com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @689604d9'
javafx.scene.control.SplitPane$Divider@4ba531b6
javafx.scene.control.SplitPane$Divider@41aaf0f8
javafx.scene.control.SplitPane$Divider@291cd1f3
javafx.scene.control.SplitPane$Divider@33e8f75c
javafx.scene.control.SplitPane$Divider@2525d539
javafx.scene.control.SplitPane$Divider@76d111bf
javafx.scene.control.SplitPane$Divider@6c4aa809
javafx.scene.control.SplitPane$Divider@388fec1d
javafx.scene.control.SplitPane$Divider@2dc3e7ed
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ExceptionInInitializerError
        at stan.qodat.Qodat.loadMainController(Qodat.kt:106)
        at stan.qodat.Qodat.start(Qodat.kt:45)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
        ... 1 more
Caused by: java.nio.BufferUnderflowException
        at java.base/java.nio.Buffer.nextGetIndex(Unknown Source)
        at java.base/java.nio.HeapByteBuffer.get(Unknown Source)
        at net.runelite.cache.io.InputStream.readByte(InputStream.java:95)
        at net.runelite.cache.io.InputStream.readUnsignedByte(InputStream.java:110)
        at net.runelite.cache.definitions.loaders.ItemLoader.load(ItemLoader.java:46)
        at net.runelite.cache.ItemManager.load(ItemManager.java:68)
        at stan.qodat.cache.impl.oldschool.OldschoolCacheRuneLite.load(OldschoolCacheRuneLite.kt:71)
        at stan.qodat.cache.impl.oldschool.OldschoolCacheRuneLite.<clinit>(OldschoolCacheRuneLite.kt:54)
        ... 11 more
```

**Comment by dosier** [comment]
This should be fixed now @LengaJenga !
